### ISSUE TITLE
How should crate2nix be used for libraries?

### ISSUE THREAD

**Issue by lovesegfault** [kolloch/crate2nix#119]
I want to use `crate2nix` to make my life easier while working on [chromaprint_sys](https://github.com/lovesegfault/chromaprint_sys/). Normally when developing a library one shouldn't include the lockfile in the repo, however I need the lockfile to use crate2nix. 

Right now I decided to check in `Cargo.nix` but not `Cargo.lock`. Is this the right approach?

**Comment by kolloch** [comment]
This is hard to answer without more context. How are you using the library?

`crate2nix` does not contain any logic (yet?) to resolve dependency versions but it relies on Cargo and `Cargo.lock` for that. 

The generated `Cargo.nix` will refer the exact library versions from the Cargo.lock file. That can be right or wrong, depending on what you want.

If you generate a `Cargo.nix` file from a binary or workspace that is referencing this library, the dependencies might or might not resolve to the same exact versions. If they resolve to the same versions, then nix is smart enough to reuse the same cached build results. Otherwise not.

**Comment by lovesegfault** [comment]
I think the approach closest to what I expect is then to check-in the `Cargo.nix` but not the `Cargo.lock`. this gives me:
* The usual behavior for Rust users, where their libs don't come with lockfiles
* Working set up for people wanting to build the crate locally with Nix

Thanks!
