### ISSUE TITLE
Don’t overwrite `default.nix` if it’s not explicitely given as input

### ISSUE THREAD

**Issue by Profpatsch** [kolloch/crate2nix#14]
It’s kind of in bad taste to overwrite existing files if the user has not explicitely specified they should be overwritten (that is by adding arguments with their name).

**Comment by kolloch** [comment]
It's the unix way! (at least partially kidding)

Anyways, I think it is quite common to overwrite an existing file in this case because you update your file. But for `default.nix` it is probably not such a great choice.

I could

* Follow your suggestion and require an overwrite flag.
* Look for a string like "Generated by crate2nix" and only overwrite if it is there.
* Change the default to `Cargo.nix` so that it is unlikely that it is used already for something else.

What do you think?

**Comment by Profpatsch** [comment]
I would just add a check if the user doesn’t specify anything explicitely; so:

`crate2nix generate -o default.nix` => overwrite file without a warning
`crate2nix generate` => if `default.nix` exists, abort with exists error, if not, just write to it.
