### ISSUE TITLE
How to add overrides to `defaultCrateOverrides`

### ISSUE THREAD

**Issue by Profpatsch** [kolloch/crate2nix#15]
The README mentions

> If your library with native dependencies is not yet supported, you can create an overlay to add the needed configuration to the `defaultCrateOverrides`

But it’s not clear to me how that can be done. For example, I can’t find the string `defaultCrateOverrides` in the generated nix file.

**Comment by kolloch** [comment]
Note that this is part of the "standard" `buildRustCrate` support that comes with NixOS. I think it would be very valuable to document this well!

Some rudimentary doc is here: https://git.mayflower.de/NixOS/nixpkgs/blob/master/doc/languages-frameworks/rust.md#compiling-rust-crates-using-nix-instead-of-cargo

I appreciate pull requests for the `README.md` for crate2nix or the nixos doc itself.

**Comment by danieldk** [comment]
Could you give a hint of how to do this? Normally `buildRustCrate` gives a derivation that is overridable. `override` expects `crateOverrides` as one of the arguments, so that something like the following works:

```
with import <nixpkgs> {};
((import ./hello.nix).hello {}).override {
  crateOverrides = defaultCrateOverrides // {
    hello = attrs: { buildInputs = [ openssl ]; };
  };
}
```

However, the file generated by crate2nix uses `makeOverrideable` again on the derivation (in `buildRustCrateWithFeatures`), for providing the feature overriding functionality. However, this seems to 'override the override', hiding the `buildRustCrate` variant?

Something like the above fails with:

```
error: anonymous function at /home/daniel/.config/nixpkgs/nix-nlp/pkgs/finalfrontier/finalfrontier.nix:2182:8 called with unexpected argument 'crateOverrides', at /home/daniel/git/nixpkgs/lib/customisation.nix:69:12
```

**Comment by danieldk** [comment]
Just to confirm, if I apply this diff to the generated Nix file, I can use `crateOverrides`:

```diff
-  buildRustCrateWithFeatures = {packageId, features}:
-    lib.makeOverridable
-      ({features}: buildRustCrateWithFeaturesImpl {inherit packageId features;})
-      { inherit features; };
+  buildRustCrateWithFeatures = buildRustCrateWithFeaturesImpl;
```

**Comment by kolloch** [comment]
You could also override the defaultCrateOverrides in pkgs with an overlay. Thanks for the detective work.

I'll add crateOverrides to the overridable parameters since it would be an incompatibility otherwise.
