### ISSUE TITLE
Error entering the shell

### ISSUE THREAD

**Issue by nuxeh** [kolloch/crate2nix#2]
I can't enter the nix-shell on a fresh install of Nix unstable on Debian, any pointers?

```
$ nix-shell
error: file 'nixos-unstable' was not found in the Nix search path (add it using $NIX_PATH or -I), at /home/ed/git/crate2nix/shell.nix:5:16

$ nix-channel --list
nixpkgs https://nixos.org/channels/nixpkgs-unstable

$ echo $NIX_PATH 
nixpkgs=/home/ed/.nix-defexpr/channels/nixpkgs
```

Thanks.

**Comment by kolloch** [comment]
Hi @nuxeh,

I tried to describe it at https://github.com/kolloch/crate2nix#installation but it is slightly confusing.

Your problem is that you have a channel pointing to `nixpkgs-unstable` but that it is called `nixpkgs`. The shell hard-codes a reference to `nixpkgs-unstable`.

This should work for you:

```bash
nix-shell --arg pkgs 'import <nixos> {config = {}; }'
```

Let me know if it doesn't!

**Comment by kolloch** [comment]
Hi @nuxeh, I also changed the `shell.nix` in such a way now that it does not depend on your local channel configuration. Let me know if it works for you!

**Comment by nuxeh** [comment]
Aha, just seen this... yes, seems to work nicely!
