### ISSUE TITLE
Question: use cases for crate2nix generated default.nix

### ISSUE THREAD

**Issue by nuxeh** [kolloch/crate2nix#7]
A general question...

I'm curious what the use cases are for the `default.nix` generated by `crate2nix`. I can see a case for using Nix and its cacheing for building during development, and locally. However, is it useful to submit the generated `default.nix` to Nixpkgs? For one thing, the generated file is very large, and for another, since rust is statically linked, the project can be built at once with `buildRustPackage` and cached as one package, once it's been cached, there should be no penalty for doing a full build with Cargo, so I don't see the advantage, and if there is, i'm curious what it is.

I'm asking since I'm thinking of submitting a package to Nixpkgs, and i'm not sure whether to add the `crate2nix` generated `default.nix` or just use the single `buildRustPackage`, which the majority of Rust packages on Nixpkgs use. It even seems to be the case that a rather small minority of Rust packages on Nixpkgs use `carnix`.

**Comment by kolloch** [comment]
Well, I guess this is an open question. My main motivation for `crate2nix` was making my custom binaries buildable/deployable with nixops. I think that `nix` has great potential for that because with more work it can then also be used for providing extensive dependencies during test (e.g. postgres). That would e.g. make it trivial to run tests against different versions of postgres prior to a migration.

For nixpkgs, I guess there is a trade-off between the size of the nix expressions and reusing cached dependencies. Also for nixpkgs if only some library dependency or the binary code has changed, it is still nice to only re-build what is necessary. If multiple binaries happen to use the exact same library dependency, it has only to been built once. How often that happens, I don't know. You could obviously do more work to ensure that binaries use the same library versions as long as they are compatible. This would be similar to adding them to one "cargo workspace". Updating their dependencies on the same snapshot of crates.io would probably already go a long way but then we would not use the locked dependencies of the upstream...

Does that make sense? I'd love to hear your opinion.
